In [2]:
import numpy as np

## up to shivam goenka
grades = [360, 270, 315, 310, 290, 275, 270, 250, 340, 310, 335, 305, 295, 315, 355]

## up to Vishal Malla
grades2 = [365, 215, 325, 320, 325, 425, 385, 320, 335, 360, 410, 365, 380, 365, 370]

## Fan Shu
grades3 = [420, 330, 315, 230, 360, 345, 405, 330, 355, 365, 350, 305, 430, 430, 330]

## Daniel Yuan
grades4 = [390, 305, 365, 145, 345, 345, 280, 370, 395, 315, 210, 405, 385, 400, 380]

## Test Student
grades5 = [245, 310, 260, 420, 0, 285, 0]

In [16]:
def convert6422(grades):
    return np.round(np.array(grades) * 375 / 460)

In [17]:
convert6422(grades)

array([293., 220., 257., 253., 236., 224., 220., 204., 277., 253., 273.,
       249., 240., 257., 289.])

In [18]:
convert6422(grades2)

array([298., 175., 265., 261., 265., 346., 314., 261., 273., 293., 334.,
       298., 310., 298., 302.])

In [19]:
convert6422(grades3)

array([342., 269., 257., 188., 293., 281., 330., 269., 289., 298., 285.,
       249., 351., 351., 269.])

In [20]:
convert6422(grades4)

array([318., 249., 298., 118., 281., 281., 228., 302., 322., 257., 171.,
       330., 314., 326., 310.])

In [21]:
convert6422(grades5)

array([200., 253., 212., 342.,   0., 232.,   0.])